name: Build and Push Image

on:
  push:
    branches: [huggingface]
    paths:
      - 'Dockerfile'
      - 'app.js'
      - 'package.json'
      - 'index.html'
  pull_request:
    branches: [huggingface]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 关键权限
      id-token: write  # 如需OIDC可加

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: huggingface

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动注入的Token

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 修改镜像名称包含仓库路径（重要！）
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:huggingface
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.description=http server
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
